services:
  # ################################################
  # 1. El motor de nuestra Base de Datos
  # ################################################
  bbdd-plataforma:
    image: postgres:15-alpine
    container_name: postgres_deportivo
    restart: always
    environment:
      POSTGRES_DB: bbdd-plataforma
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - data-deportiva:/var/lib/postgresql/data
    networks:
      - red-deportiva

  # ################################################
  # 2. Tu Microservicio de Autenticación (¡NUEVO!)
  # ################################################
  auth-service:
    container_name: auth_service_container
    restart: always
    build:
      context: ./backend-services/auth_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Apuntamos la URL al nombre del contenedor de la BBDD 'bbdd-plataforma'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bbdd-plataforma:5432/bbdd-plataforma
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123456789
    depends_on:
      - bbdd-plataforma
    networks:
      - red-deportiva

# Volúmenes para que los datos no se borren al apagar el contenedor
volumes:
  data-deportiva:

# Red interna para que los microservicios se hablen entre sí en el futuro
networks:
  red-deportiva:
    driver: bridge