# 1. Identificación del microservicio
# El nombre del microservicio es "auth-service" y se ejecutará en el puerto 8081. 
# Esto es importante para la comunicación entre microservicios y para la configuración de rutas en el API Gateway.
spring.application.name=auth_service
server.port=8081

# 2. Configuración de la conexión a la Base de Datos (JDBC)
# En este caso, se está utilizando PostgreSQL como base de datos.
# La URL de conexión especifica el host (localhost), el puerto (5432) y el nombre de la base de datos (bbdd-plataforma).
# Las credenciales de acceso son el usuario "admin" y la contraseña "123456789".
# El driver JDBC para PostgreSQL es "org.postgresql.Driver". Asegúrate de tener esta dependencia en tu proyecto para que la conexión funcione correctamente.
# Nota: En un entorno de producción, es recomendable no hardcodear las credenciales en el archivo de configuración. En su lugar, se pueden utilizar variables de entorno o servicios de gestión de secretos para proteger esta información sensible.
spring.datasource.url=jdbc:postgresql://localhost:5432/bbdd-plataforma
spring.datasource.username=admin
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Estrategia de JPA / Hibernate
# La propiedad "spring.jpa.hibernate.ddl-auto" se establece en "update", lo que significa que Hibernate actualizará automáticamente el esquema de la base de datos según las entidades definidas en el código.
# Esto es útil durante el desarrollo, pero en producción se recomienda utilizar "validate" o "none" para evitar cambios no deseados en la base de datos.
# Las propiedades "spring.jpa.show-sql" y "spring.jpa.properties.hibernate.format_sql" se utilizan para mostrar las consultas SQL generadas por Hibernate en la consola de logs, lo que facilita la depuración y el monitoreo de las operaciones de la base de datos.
# Recuerda que estas configuraciones pueden ser ajustadas según las necesidades específicas de tu proyecto y el entorno en el que se despliegue.
# En un entorno de producción, es posible que desees desactivar la visualización de SQL para mejorar el rendimiento y reducir la cantidad de información sensible que se muestra en los logs.
# En resumen, este archivo de configuración establece las bases para la conexión a la base de datos y la gestión de entidades en el microservicio de autenticación, asegurando que el servicio pueda interactuar correctamente con la base de datos y facilitar el desarrollo y la depuración.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
