# 1. Identificación del microservicio
spring.application.name=auth-service
server.port=8081

# 2. Configuración de la conexión a la Base de Datos (JDBC)
spring.datasource.url=jdbc:postgresql://localhost:5432/bbdd-plataforma
spring.datasource.username=admin
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Estrategia de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true